require_relative 'module/add_item_info'
require_relative 'module/save_load_book'
require 'date'
require 'json'
require_relative 'item_class'
require_relative 'games'
require_relative 'authors'
require_relative 'catalog_management'
require_relative 'game_author'
require_relative 'menu'
require_relative 'genres'
require_relative 'book'
require_relative 'label'

require_relative 'music_album'
