CREATE TABLE item (
  id INT SERIAL PRIMARY KEY,
  genre INT REFERENCES genre(id),
  author INT REFERENCES author(id),
  source INT REFERENCES source(id),
  label INT REFERENCES label(id),
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL
);

CREATE TABLE musicAlbum (
  id INT PRIMARY KEY REFERENCES item(id),
  on_spotify BOOLEAN NOT NULL
);

CREATE TABLE genre (
  id INT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE author (
  id INT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL
);

CREATE TABLE label (
  id INT PRIMARY KEY,
  title VARCHAR(30),
  color VARCHAR(20)
);

CREATE TABLE sources (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE game (
  id INT PRIMARY KEY,
  multiplayer VARCHAR(30) NOT NULL,
  last_played_at DATE NOT NULL
);

CREATE TABLE book (
  id INT PRIMARY KEY,
  publisher VARCHAR(40),
  cover_state VARCHAR(30)
);

ALTER TABLE "game" ADD FOREIGN KEY ("id") REFERENCES "item" ("id");

ALTER TABLE "book" ADD FOREIGN KEY ("id") REFERENCES "item" ("id");

ALTER TABLE "movies" ADD FOREIGN KEY ("id") REFERENCES "item" ("id");